"""create vector_stores files file_chunks tables

Revision ID: 5e4cb5abbe73
Revises: 
Create Date: 2026-02-13 15:49:04.964192

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector  # noqa: F401
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e4cb5abbe73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types with IF NOT EXISTS to handle databases where the
    # schema was already created outside of Alembic (e.g. via create_all).
    vector_store_status = postgresql.ENUM(
        'expired', 'in_progress', 'completed',
        name='vector_store_status', create_type=False,
    )
    op.execute(sa.text("""
        DO $$ BEGIN
            CREATE TYPE vector_store_status AS ENUM ('expired', 'in_progress', 'completed');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """))

    file_status = postgresql.ENUM(
        'in_progress', 'completed', 'cancelled', 'failed',
        name='file_status', create_type=False,
    )
    op.execute(sa.text("""
        DO $$ BEGIN
            CREATE TYPE file_status AS ENUM ('in_progress', 'completed', 'cancelled', 'failed');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """))

    bind = op.get_bind()
    insp = inspect(bind)

    if not insp.has_table('vector_stores'):
        op.create_table('vector_stores',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('file_counts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('status', vector_store_status, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if not insp.has_table('files'):
        op.create_table('files',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('vector_store_id', sa.Uuid(), nullable=False),
        sa.Column('filename', sa.String(length=1024), nullable=False),
        sa.Column('status', file_status, nullable=False),
        sa.Column('bytes', sa.Integer(), nullable=False),
        sa.Column('purpose', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['vector_store_id'], ['vector_stores.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )

    if not insp.has_table('file_chunks'):
        op.create_table('file_chunks',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('vector_store_id', sa.Uuid(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('token_count', sa.Integer(), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['vector_store_id'], ['vector_stores.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )

    if 'ix_file_chunks_embedding_hnsw' not in [idx['name'] for idx in insp.get_indexes('file_chunks')]:
        op.create_index('ix_file_chunks_embedding_hnsw', 'file_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_chunks_embedding_hnsw', table_name='file_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('file_chunks')
    op.drop_table('files')
    op.drop_table('vector_stores')
    # ### end Alembic commands ###
